### ISSUE TITLE
Investigate nbdev

### ISSUE THREAD

**Issue by rabernat** [hscannell/ocetrac_dev#1]
Since all your code is already in notebooks, we might want to use the nbdev framework for this project. 

https://github.blog/2020-11-20-nbdev-a-literate-programming-environment-that-democratizes-software-engineering-best-practices/

**Comment by hscannell** [comment]
I like that idea. I wonder if memory usage would pose any issues, especially with a large dataset.

**Comment by rabernat** [comment]
Nbdev is a framework for developing packages. It places no constraints on memory use.

**Comment by hscannell** [comment]
I've migrated ocetrac to use nbdev [here](https://github.com/hscannell/ocetrac)
